/*
  Warnings:

  - You are about to alter the column `id` on the `Solutions` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `question_id` on the `Solutions` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `course_id` on the `Topics` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Int`.
  - You are about to alter the column `id` on the `Topics` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `id` on the `User` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `id` on the `CourseInfo` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `count` on the `Subproblems` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Int`.
  - You are about to alter the column `id` on the `Subproblems` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `question_id` on the `Subproblems` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Int`.
  - You are about to alter the column `id` on the `Questions` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `topic_id` on the `Questions` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Int`.
  - Changed the type of `user_id` on the `QuestionsDone` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.
  - Changed the type of `question_id` on the `QuestionsDone` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- DropForeignKey
ALTER TABLE "QuestionsDone" DROP CONSTRAINT "QuestionsDone_question_id_fkey";

-- DropForeignKey
ALTER TABLE "QuestionsDone" DROP CONSTRAINT "QuestionsDone_user_id_fkey";

-- AlterTable
ALTER TABLE "QuestionsDone" DROP COLUMN "user_id";
ALTER TABLE "QuestionsDone" ADD COLUMN     "user_id" INT4 NOT NULL;
ALTER TABLE "QuestionsDone" DROP COLUMN "question_id";
ALTER TABLE "QuestionsDone" ADD COLUMN     "question_id" INT4 NOT NULL;

-- RedefineTables
CREATE TABLE "_prisma_new_Solutions" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "question_id" INT4 NOT NULL,
    "solution" STRING NOT NULL,

    CONSTRAINT "Solutions_pkey" PRIMARY KEY ("id")
);
DROP INDEX "Solutions_question_id_key";
INSERT INTO "_prisma_new_Solutions" ("id","question_id","solution") SELECT "id","question_id","solution" FROM "Solutions";
DROP TABLE "Solutions" CASCADE;
ALTER TABLE "_prisma_new_Solutions" RENAME TO "Solutions";
CREATE UNIQUE INDEX "Solutions_question_id_key" ON "Solutions"("question_id");
ALTER TABLE "Solutions" ADD CONSTRAINT "Solutions_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "Questions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "_prisma_new_Topics" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "topic_name" STRING NOT NULL,
    "course_id" INT4 NOT NULL,

    CONSTRAINT "Topics_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_Topics" ("course_id","id","topic_name") SELECT "course_id","id","topic_name" FROM "Topics";
DROP TABLE "Topics" CASCADE;
ALTER TABLE "_prisma_new_Topics" RENAME TO "Topics";
ALTER TABLE "Topics" ADD CONSTRAINT "Topics_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "CourseInfo"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "_prisma_new_User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" STRING NOT NULL,
    "last_name" STRING NOT NULL,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
DROP INDEX "User_email_key";
INSERT INTO "_prisma_new_User" ("email","first_name","id","last_name","password") SELECT "email","first_name","id","last_name","password" FROM "User";
DROP TABLE "User" CASCADE;
ALTER TABLE "_prisma_new_User" RENAME TO "User";
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "_prisma_new_CourseInfo" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "course_name" STRING NOT NULL,

    CONSTRAINT "CourseInfo_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_CourseInfo" ("course_name","id") SELECT "course_name","id" FROM "CourseInfo";
DROP TABLE "CourseInfo" CASCADE;
ALTER TABLE "_prisma_new_CourseInfo" RENAME TO "CourseInfo";
CREATE TABLE "_prisma_new_Subproblems" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "count" INT4 NOT NULL,
    "question_id" INT4 NOT NULL,
    "title" STRING NOT NULL,
    "description" STRING NOT NULL,

    CONSTRAINT "Subproblems_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_Subproblems" ("count","description","id","question_id","title") SELECT "count","description","id","question_id","title" FROM "Subproblems";
DROP TABLE "Subproblems" CASCADE;
ALTER TABLE "_prisma_new_Subproblems" RENAME TO "Subproblems";
ALTER TABLE "Subproblems" ADD CONSTRAINT "Subproblems_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "Questions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "_prisma_new_Questions" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "question" STRING NOT NULL,
    "topic_id" INT4 NOT NULL,
    "hint" STRING NOT NULL,

    CONSTRAINT "Questions_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_Questions" ("hint","id","question","topic_id") SELECT "hint","id","question","topic_id" FROM "Questions";
DROP TABLE "Questions" CASCADE;
ALTER TABLE "_prisma_new_Questions" RENAME TO "Questions";
ALTER TABLE "Questions" ADD CONSTRAINT "Questions_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "Topics"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuestionsDone" ADD CONSTRAINT "QuestionsDone_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuestionsDone" ADD CONSTRAINT "QuestionsDone_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "Questions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
